[tool.poetry]
name = "stairlight"
version = "0.3.2"
description = "Table-level data lineage tool"
authors = ["tosh2230 <rev.to12@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.2"
PyYAML = ">=5.0"
Jinja2 = ">=2.10.3"
google-cloud-storage = "^1.28.1"
SQLAlchemy = "^1.4.31"
psycopg2 = "^2.9.3"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
isort = "^5.9.3"
pytest = "^6.2.5"
black = "^21.9b0"
pytest-cov = "^3.0.0"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.poetry.scripts]
stairlight = "stairlight.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
