mapping:
  - file: 'tests/sql/a/test_a.sql'
    table: 'PROJECT_X.DATASET_Y.TABLE_A'
    params:
      - param_a:
        - a: a
          b: b
        - a: aa
          b: bb
        - a: aaa
          b: bbb
      - param_x:
        - x: x
          y: y
        - x: xx
          y: yy
        - x: xxx
          y: yyy
  - file: 'tests/sql/b/test_b.sql'
    table: 'PROJECT_X.DATASET_Y.TABLE_B'
exclude:
  - 'tests/sql/c/test_exclude.sql'