Mapping:
  - TemplateSourceType: GCS
    Uri: gs://stairlight/sql/one_line/one_line.sql
    Tables:
      - TableName: PROJECT_A.DATASET_1.TABLE_1
  - TemplateSourceType: GCS
    Uri: gs://stairlight/sql/cte/cte_multi_line.sql
    Tables:
      - TableName: Organization.Repository.AppName
        Parameters:
          params:
            PROJECT: "PROJECT_A"
            DATASET: DATASET_1
            TABLE: TABLE_1
