Mapping:
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_a.sql"
    Tables:
      - TableName: "PROJECT_A.DATASET_B.TABLE_C"
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_b.sql"
    Tables:
      - TableName: "PROJECT_D.DATASET_E.TABLE_F"
        Parameters:
          params:
            PROJECT: PROJECT_J
            DATASET: DATASET_K
            TABLE: TABLE_L
        Labels:
          Source: file
          Test: b
      - TableName: "PROJECT_G.DATASET_H.TABLE_I"
        Parameters:
          params:
            PROJECT: PROJECT_M
            DATASET: DATASET_N
            TABLE: TABLE_O
        Labels:
          Source: file
          Test: b
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_c.sql"
    Tables:
      - TableName: "PROJECT_J.DATASET_K.TABLE_L"
        Parameters:
          params:
            main_table: "PROJECT_P.DATASET_Q.TABLE_R"
            sub_table_01: "PROJECT_S.DATASET_T.TABLE_U"
            sub_table_02: "PROJECT_V.DATASET_W.TABLE_X"
        Labels:
          Source: file
          Test: c
  - TemplateSourceType: GCS
    Uri: "gs://stairlight/sql/test_a/test_a.sql"
    Tables:
      - TableName: "PROJECT_a.DATASET_b.TABLE_c"
  - TemplateSourceType: GCS
    Uri: "gs://stairlight/sql/test_b/test_b.sql"
    Tables:
      - TableName: "PROJECT_d.DATASET_e.TABLE_f"
        Parameters:
          params:
            PROJECT: PROJECT_g
            DATASET: DATASET_h
            TABLE: TABLE_i
        Labels:
          Source: gcs
          Test: b
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_d.sql"
    Tables:
      - TableName: "PROJECT_j.DATASET_k.TABLE_l"
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_e.sql"
    Tables:
      - TableName: "PROJECT_d.DATASET_e.TABLE_f"
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_f.sql"
    Tables:
      - TableName: "PROJECT_d.DATASET_d.TABLE_d"
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_undefined_part.sql"
    Tables:
      - TableName: "PROJECT_u.DATASET_u.TABLE_u"
        Parameters:
          params:
            main_table: "PROJECT_t.DATASET_t.TABLE_t"
  - TemplateSourceType: File
    FileSuffix: "tests/sql/main/test_union_same_table.sql"
    Tables:
      - TableName: "test_project.beam_streaming.taxirides_aggregation"
  - TemplateSourceType: Redash
    QueryId: 5
    DataSourceName: metadata
    Tables:
      - TableName: Copy of (#4) New Query
        Parameters:
          table: dashboards
        Labels:
          Category: Redash test
Metadata:
  - TableName: "PROJECT_A.DATASET_A.TABLE_A"
    Labels:
      Source: Null
      Test: a
