mapping:
  - file_suffix: "tests/sql/main/test_a.sql"
    table: "PROJECT_A.DATASET_B.TABLE_C"
  - file_suffix: "tests/sql/main/test_b.sql"
    table: "PROJECT_D.DATASET_E.TABLE_F"
    params:
      PROJECT: PROJECT_J
      DATASET: DATASET_K
      TABLE: TABLE_L
  - file_suffix: "tests/sql/main/test_b.sql"
    table: "PROJECT_G.DATASET_H.TABLE_I"
    params:
      PROJECT: PROJECT_M
      DATASET: DATASET_N
      TABLE: TABLE_O
  - file_suffix: "tests/sql/main/test_c.sql"
    table: "PROJECT_J.DATASET_K.TABLE_L"
    params:
      main_table: "PROJECT_P.DATASET_Q.TABLE_R"
      sub_table_01: "PROJECT_S.DATASET_T.TABLE_U"
      sub_table_02: "PROJECT_V.DATASET_W.TABLE_X"
  - bucket: "stairlight"
    file_suffix: "sql/test_a/test_a.sql"
    table: "PROJECT_a.DATASET_b.TABLE_c"
  - bucket: "stairlight"
    file_suffix: "sql/test_b/test_b.sql"
    table: "PROJECT_d.DATASET_e.TABLE_f"
    params:
      PROJECT: PROJECT_g
      DATASET: DATASET_h
      TABLE: TABLE_i
  - file_suffix: "tests/sql/main/test_d.sql"
    table: "PROJECT_j.DATASET_k.TABLE_l"
  - file_suffix: "tests/sql/main/test_e.sql"
    table: "PROJECT_z.DATASET_z.TABLE_z"
