sources:
  - type: fs
    path: "./tests/sql"
    regex: ".*/*.sql$"
    default_table_prefix: "PROJECT_A"
  - type: gcs
    project: null
    bucket: stairlight
    regex: "^sql/.*/*.sql$"
    default_table_prefix: "PROJECT_A"
exclude:
  - type: fs
    regex: "main/test_exclude.sql$"
logging:
  level: INFO
  fmt: "%(asctime)s.%(msecs)03d %(filename)s:%(funcName)s:%(lineno)d [%(levelname)s]%(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
