sources:
  - type: fs
    path: "./tests/sql"
    pattern: "**/*.sql"
  - type: gcs
    project: null
    bucket: stairlight
    prefix: "sql/"
  - type: s3
    path: "s3://stairlighttest"
    pattern: "**/*.sql"
exclude:
  - "tests/sql/main/test_exclude.sql"
logging:
  level: INFO
  fmt: "%(asctime)s.%(msecs)03d %(filename)s:%(funcName)s:%(lineno)d [%(levelname)s]%(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
