Include:
  - TemplateSourceType: File
    FileSystemPath: "./tests/sql"
    Regex: ".*/*.sql$"
    DefaultTablePrefix: "PROJECT_A"
  - TemplateSourceType: GCS
    ProjectId: null
    BucketName: stairlight
    Regex: "^sql/.*/*.sql$"
    DefaultTablePrefix: "PROJECT_A"
  # - TemplateSourceType: redash
  #   ConnStrEnvVariable: REDASH_DATABASE_URL
  #   DataSourceName: ""
  #   QueryIds:
  #     - 1
  #     - 3
  #     - 5
Exclude:
  - TemplateSourceType: File
    Regex: "main/test_exclude.sql$"
Settings:
  MappingPrefix: "mapping"
