sources:
  - type: fs
    path: "./tests/sql"
    regex: ".*/*.sql"
  - type: gcs
    project: null
    bucket: stairlight
    regex: "sql/.*/*.sql"
  - type: s3
    bucket: stairlight
    regex: "**/*.sql"
exclude:
  - "tests/sql/main/test_exclude.sql"
logging:
  level: DEBUG
  fmt: "%(asctime)s.%(msecs)03d %(filename)s:%(funcName)s:%(lineno)d [%(levelname)s]%(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
