name: Setup
description: Setup environment
inputs:
  GCP_PROJECT_ID:
    description: GCP_PROJECT_ID
    required: true
  GCP_WORKLOAD_IDP:
    description: GCP_WORKLOAD_IDP
    required: true
  GCP_SERVICE_ACCOUNT:
    description: GCP_SERVICE_ACCOUNT
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --extras "gcs redash"
      shell: bash
    - name: Setup Google Cloud
      uses: "google-github-actions/setup-gcloud@v0"
      with:
        project_id: ${{ inputs.GCP_PROJECT_ID }}
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.1
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDP }}
        service_account: ${{ inputs.GCP_SERVICE_ACCOUNT }}
        access_token_lifetime: 300s
    - name: Login to Google Cloud with workload IdP
      run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      shell: bash
