name: CI
on: [push]
permissions:
  contents: read
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Setup Google Cloud
        uses: "google-github-actions/setup-gcloud@master"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.3.1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - name: Login to Google Cloud with workload IdP
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      - name: Check linting
        run: |
          make lint
      - name: Setup
        run: |
          # make setup-gcs

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Setup Google Cloud
        uses: "google-github-actions/setup-gcloud@master"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.3.1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - name: Login to Google Cloud with workload IdP
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      - name: Unit test
        run: |
          poetry run pytest -v --cov=src
